# Generated by Django 4.1.7 on 2023-03-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoapp',
            options={'verbose_name': 'TODO', 'verbose_name_plural': 'TODO'},
        ),
        migrations.AlterField(
            model_name='todoapp',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
